import assert from 'node:assert/strict';
import {DraftOutbox,buildPrimaryUpdate,rotatePrimary} from '../web/src/sync.js';
const tick=()=>new Promise(r=>setTimeout(r,0));
const draft=()=>({draft_id:'d',epoch:'e',revision:0,generation:0,text:'A',assets:[]});
const calls=[]; const jobs=new Map();let i=0;
const saved=[];
const q=new DraftOutbox({send:m=>calls.push(m),persist:async()=>saved.push('saved'),timer:(f,_ms)=>{jobs.set(++i,f);return i},cancel:id=>jobs.delete(id)});
const state=draft();q.offer(buildPrimaryUpdate(state,'m1'));assert.equal(calls.length,0);
q.connect();await tick();assert.equal(calls.length,1);assert.equal(saved.length,1);
state.text='B';q.offer(buildPrimaryUpdate(state,'m2'));state.text='C';q.offer(buildPrimaryUpdate(state,'m3'));
assert.equal(calls.length,1);assert.equal(q.latest.text,'C');
assert.equal(q.acknowledge({...calls[0],update_id:'wrong',durable:true}),false);
[...jobs.values()][0]();assert.equal(calls.length,2);assert.deepEqual(calls[0],calls[1]);
q.acknowledge({...calls[0],durable:true});await tick();assert.equal(calls.length,3);assert.equal(calls[2].text,'C');
q.acknowledge({...calls[2],durable:true});await q.flush('m3');
q.disconnect();state.text='离线';q.offer(buildPrimaryUpdate(state,'m4'));q.connect();await tick();assert.equal(calls.at(-1).text,'离线');q.close();
const s=draft();s.revision=3;
const receipt={phone_primary:true,rotated:true,generation:0,archived:{draft_id:'d',epoch:'e',revision:3,source_text:'A',asset_refs:[],assets:[]}};
assert.equal(rotatePrimary(s,receipt,()=> 'phone-next'),'cleared');assert.equal(s.epoch,'phone-next');assert.equal(s.generation,1);
assert.equal(rotatePrimary(s,receipt,()=> 'bad'),'kept');
const b=draft();b.revision=3;b.assets=[{id:'new',status:'editing'}];assert.equal(rotatePrimary(b,receipt,()=> 'bad'),'kept');assert.equal(b.assets.length,1);
console.log('primary outbox: coalescing, idempotent retry, matching ACK, offline continuation, safe local rotation passed');
