"""由同一主题源生成 Qt/CSS 色值；--check 校验没有手改或遗漏。"""
from pathlib import Path
import argparse, json
ROOT=Path(__file__).resolve().parents[1]
def outputs():
    value=json.loads((ROOT/'assets/ui-theme.json').read_text(encoding='utf-8'))
    colors=value['colors'];metrics=value['metrics']
    py='# Generated by tools/export_ui_theme.py; edit assets/ui-theme.json instead.\nCOLORS = '+repr(colors)+'\nMETRICS = '+repr(metrics)+'\n'
    css='/* Generated from assets/ui-theme.json. */\n:root {\n'+''.join('  --'+k.replace('_','-')+': '+v+';\n' for k,v in colors.items())+''.join('  --'+k.replace('_','-')+': '+str(v)+'px;\n' for k,v in metrics.items())+'  color-scheme: light;\n}\n'
    return {ROOT/'src/doubao_typeless/ui/theme_generated.py':py,ROOT/'web/src/theme.generated.css':css}
def main():
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
    for path,text in outputs().items():
        if a.check:
            if not path.exists() or path.read_text(encoding='utf-8')!=text:raise SystemExit('Theme output differs: '+str(path.relative_to(ROOT)))
        else:path.write_text(text,encoding='utf-8')
if __name__=='__main__':main()
